version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
  dockerspringboot:
    image: dockerspringboot:1.0
    container_name: dockerspringboot
    ports:
      - 6040:6040
    links:
      - mongodb
    